In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

np.set_printoptions(precision=3, linewidth=500, threshold=500, suppress=True, edgeitems=5)

pd.set_option('display.max_rows', 200)
pd.set_option('display.min_rows', 50)
pd.set_option('display.width', 1000)
pd.set_option('display.max_columns', 100)

%load_ext autoreload
%autoreload 2
%matplotlib notebook

In [2]:
from numpy.random import randn
from numpy import diag, ndarray



In [3]:
import sys
sys.path.append('..')

In [5]:
from utils.kronecker import KroneckerOperator, KroneckerProduct, KroneckerSum, KroneckerDiag, _ProductChain, _SumChain
from utils.linalg import kronecker_product_literal, kronecker_sum_literal, vec, ten


In [87]:
N1 = 6
N2 = 5
N3 = 4
N4 = 3

A1 = randn(N1, N1)
A2 = randn(N2, N2)
A3 = randn(N3, N3)
A4 = randn(N4, N4)


A11 = randn(N1, N1)
A22 = randn(N2, N2)
A33 = randn(N3, N3)
A44 = randn(N4, N4)

X = randn(N4, N3, N2, N1)
D = randn(N4, N3, N2, N1)

In [90]:
import time
for x in range (0,5):  
    b = "Loading" + "." * x
    print (b, end="\r")
    time.sleep(1)

In [104]:
a = np.zeros_like(X)
a[0, 2, 1, 3] = 1

np.argwhere(vec(a))

array([[198]])

In [108]:
b = np.zeros_like(vec(X))
b[122] = 1

np.argwhere(ten(b, like=X))

array([[2, 0, 0, 2]])

In [124]:
def vec_index(element, shape):
    return int(sum(n * np.prod(shape[:k]) for k, n in enumerate(element)))

def ten_index(offset, shape):
    
    out = []
    
    for N in shape:
    
        x = offset % N
        offset = offset // N
        out.append(x)
        

    return out


In [160]:
dir(A1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [166]:
from pprint import pprint

In [169]:
matrix = [["A", "B", 'ffffff'], ["C", "D", 'aa'], ['d', 'aaaaaa', 'g']]

print('\n'.join(['\t'.join([str(cell) for cell in row]) for row in matrix]))

A	B	ffffff
C	D	aa
d	aaaaaa	g


In [ ]:
''.join(['[' + ', '.join([to_string('ff') for j in range(self.n_blocks)]) + ']' for i in range(self.n_blocks)])

In [143]:
np.concatenate([np.array([[1, 2, 3]]), np.array([[1, 12, 4]])], axis=0)

array([[ 1,  2,  3],
       [ 1, 12,  4]])

In [147]:
[0] + np.cumsum(a).tolist()

[0, 3, 7]

In [76]:
a = np.array([1, 2, 3, 4])

In [77]:
ma = np.ma.masked_array(a, mask=[0, 0, 1, 0])

In [80]:
type(ma)

numpy.ma.core.MaskedArray

In [82]:
isinstance(ma, ndarray)

True

In [86]:
ma.data

array([1, 2, 3, 4])

In [85]:
~np.isnan([np.nan, 4, 5, 6])

array([False,  True,  True,  True])